# Generated by Django 4.0.5 on 2022-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyOnline', '0002_commande_produit_produitcommande_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
