# Generated by Django 4.1 on 2022-10-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyOnline', '0003_rename_client_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='clients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BuyOnline.clients'),
        ),
    ]
