# Generated by Django 4.0.5 on 2022-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyOnline', '0003_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
