# Generated by Django 4.1 on 2022-10-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyOnline', '0004_alter_commande_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuyOnline.clients'),
        ),
    ]
