# Generated by Django 4.1 on 2022-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyOnline', '0005_alter_commande_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='ordered',
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='non livré', max_length=15),
        ),
    ]
