# Generated by Django 4.1 on 2022-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyOnline', '0006_remove_commande_ordered_commande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitcommande',
            name='ordered',
        ),
        migrations.AddField(
            model_name='produitcommande',
            name='statut',
            field=models.CharField(default='non livré', max_length=15),
        ),
    ]
